[build]
  command = "npm run build"
  publish = "build"

[build.environment]
  # Wyłączenie traktowania ostrzeżeń ESLint jako błędów
  CI = "false" 

# Konfiguracja nagłówków bezpieczeństwa
[[headers]]
  for = "/*"
  [headers.values]
    # Zapobieganie clickjacking
    X-Frame-Options = "DENY"
    # Zapobieganie MIME sniffing
    X-Content-Type-Options = "nosniff"
    # Ochrona przed XSS
    X-XSS-Protection = "1; mode=block"
    # Polityka odnośników
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Polityka bezpieczeństwa zawartości
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' 'unsafe-eval' https://www.googletagmanager.com https://pagead2.googlesyndication.com https://*.google.com https://*.googleadservices.com https://*.googlesyndication.com https://*.doubleclick.net; style-src 'self' 'unsafe-inline' https://fonts.googleapis.com https://fonts.gstatic.com; img-src 'self' https://suppi.pl data: https://*.google.com https://*.googleapis.com https://*.gstatic.com https://*.googlesyndication.com https://*.doubleclick.net; connect-src 'self' https://api.airtable.com https://api-sdp.stat.gov.pl https://*.google-analytics.com https://*.analytics.google.com https://*.googleadservices.com https://*.googlesyndication.com https://*.doubleclick.net; font-src 'self' data: https://fonts.googleapis.com https://fonts.gstatic.com; frame-src 'self' https://*.googlesyndication.com https://*.doubleclick.net;"
    # Zapobieganie cachowaniu danych wrażliwych
    Cache-Control = "no-store, max-age=0"

# Funkcje Netlify
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild" 