[build]
  functions = "netlify/functions"
  publish = "kalkulator-finansowy-nieruchomosci/build"

[build.environment]
  # Wyłączenie traktowania ostrzeżeń ESLint jako błędów
  CI = "false" 

[dev]
  command = "npm start"
  port = 8888
  targetPort = 3000
  publish = "build"
  framework = "#custom"
  autoLaunch = true

# Konfiguracja nagłówków bezpieczeństwa
[[headers]]
  for = "/*"
  [headers.values]
    # Zapobieganie clickjacking
    X-Frame-Options = "DENY"
    # Zapobieganie MIME sniffing
    X-Content-Type-Options = "nosniff"
    # Ochrona przed XSS
    X-XSS-Protection = "1; mode=block"
    # Polityka odnośników
    Referrer-Policy = "strict-origin-when-cross-origin"
    # Najbardziej liberalna polityka CSP - do zastosowania tylko w ostateczności
    Content-Security-Policy = "default-src * data: blob: 'unsafe-inline' 'unsafe-eval'; script-src * data: blob: 'unsafe-inline' 'unsafe-eval'; connect-src * data: blob: 'unsafe-inline'; img-src * data: blob: 'unsafe-inline'; frame-src * data: blob:; style-src * data: blob: 'unsafe-inline'; font-src * data: blob: 'unsafe-inline';"
    # Zapobieganie cachowaniu danych wrażliwych
    Cache-Control = "no-store, max-age=0"

# Funkcje Netlify
[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200
