[phases.setup]
nixPkgs = ["...", "python311", "python311Packages.numpy", "python311Packages.pandas", "python311Packages.scikit-learn", "python311Packages.xgboost", "python311Packages.lightgbm", "python311Packages.joblib"]

[phases.install]
cmds = ["npm install"] 