[phases.setup]
nixPkgs = ["...", "python311", "python311Packages.pip"]

[phases.install]
cmds = ["npm install", "python -m venv venv", "source venv/bin/activate && pip install --upgrade pip", "source venv/bin/activate && pip install -r requirements-railway.txt"]

[phases.build]
cmds = ["npm run build"]

[start]
cmd = "source venv/bin/activate && npm start" 