// Słownik tłumaczeń i formaterów dla różnych typów kalkulacji
export const FIELD_DEFINITIONS: { [key: string]: { label: string; format?: (value: any) => string; order: number } } = {
  // Dane wejściowe wyceny
  city: { label: 'Miasto', order: 1 },
  district: { label: 'Dzielnica', order: 2 },
  street: { label: 'Ulica', order: 3 },
  area: { label: 'Powierzchnia', format: (v) => `${v} m²`, order: 4 },
  rooms: { label: 'Liczba pokoi', order: 5 },
  floor: { label: 'Piętro', order: 6 },
  totalFloors: { label: 'Liczba pięter w budynku', order: 7 },
  year: { label: 'Rok budowy', order: 8 },
  lastRenovation: { label: 'Rok ostatniego remontu', order: 9 },
  locationTier: { label: 'Klasa lokalizacji', format: (v: string) => ({ premium: 'Premium', standard: 'Standard', budget: 'Budżetowa' }[v] || v), order: 10 },
  condition: { label: 'Stan mieszkania', format: (v: string) => ({ new: 'Nowe', good: 'Dobry', 'to_renovate': 'Do remontu' }[v] || v), order: 11 },
  buildingType: { label: 'Typ budynku', format: (v: string) => ({ blok: 'Blok', kamienica: 'Kamienica', apartamentowiec: 'Apartamentowiec' }[v] || v), order: 12 },
  buildingMaterial: { label: 'Materiał budynku', format: (v: string) => ({ brick: 'Cegła', 'brick_concrete': 'Cegła/Beton', 'wielka_plyta': 'Wielka płyta', other: 'Inny' }[v] || v), order: 13 },
  parking: { label: 'Miejsce parkingowe', format: (v: string) => ({ garage: 'Garaż', dedicated: 'Dedykowane', street: 'Przy ulicy', none: 'Brak' }[v] || v), order: 14 },
  finishing: { label: 'Standard wykończenia', format: (v: string) => ({ high: 'Wysoki', standard: 'Standard', basic: 'Podstawowy' }[v] || v), order: 15 },
  elevator: { label: 'Winda', format: (v) => v === 'yes' ? 'Tak' : 'Nie', order: 16 },
  balcony: { label: 'Balkon/Taras', format: (v) => v === 'yes' ? 'Tak' : 'Nie', order: 17 },
  balconyArea: { label: 'Powierzchnia balkonu', format: (v) => `${v} m²`, order: 18 },
  orientation: { label: 'Ekspozycja okien', format: (v: string) => ({ north: 'Północ', south: 'Południe', east: 'Wschód', west: 'Zachód' }[v] || v), order: 19 },
  transport: { label: 'Dostęp do transportu', format: (v: string) => ({ excellent: 'Doskonały', good: 'Dobry', medium: 'Średni', poor: 'Słaby' }[v] || v), order: 20 },
  heating: { label: 'Ogrzewanie', format: (v: string) => ({ central: 'Miejskie', gas: 'Gazowe', electric: 'Elektryczne' }[v] || v), order: 21 },
  bathrooms: { label: 'Liczba łazienek', order: 22 },
  kitchenType: { label: 'Typ kuchni', format: (v: string) => ({ separate: 'Oddzielna', kitchenette: 'Aneks', open: 'Otwarta' }[v] || v), order: 23 },
  basement: { label: 'Piwnica/Komórka', format: (v: string) => v === 'basement' ? 'Tak' : 'Nie', order: 24 },
  ownership: { label: 'Forma własności', format: (v: string) => ({ full: 'Pełna własność', cooperative: 'Spółdzielcze' }[v] || v), order: 25 },
  
  // Dane wejściowe zakupu nieruchomości
  propertyValue: { label: 'Wartość nieruchomości', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 1 },
  loanAmount: { label: 'Kwota kredytu', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 2 },
  loanTerm: { label: 'Okres kredytowania', format: (v) => `${v} lat`, order: 3 },
  bankMargin: { label: 'Marża banku', format: (v) => `${v}%`, order: 4 },
  referenceRate: { label: 'Stopa referencyjna', format: (v) => `${v}%`, order: 5 },
  installmentType: { label: 'Typ rat', format: (v: string) => ({ equal: 'Równe', decreasing: 'Malejące' }[v] || v), order: 6 },
  bankCommission: { label: 'Prowizja banku', format: (v) => `${v}%`, order: 7 },
  agencyCommission: { label: 'Prowizja agencji', format: (v) => `${v}%`, order: 8 },
  pcctaxRate: { label: 'Stawka PCC', format: (v) => `${v}%`, order: 9 },
  notaryFeeType: { label: 'Typ taksy notarialnej', format: (v: string) => ({ max: 'Maksymalna', custom: 'Własna' }[v] || v), order: 10 },
  customNotaryFee: { label: 'Własna taksa notarialna', format: (v) => v ? new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v) : 'Brak', order: 11 },
  referenceRateChange: { label: 'Zmiana stopy referencyjnej', format: (v) => `${v}%`, order: 12 },
  bridgeInsuranceMonths: { label: 'Okres ubezpieczenia pomostowego', format: (v) => `${v} miesięcy`, order: 13 },
  bridgeInsuranceMarginIncrease: { label: 'Zwiększenie marży pomostowej', format: (v) => `${v}%`, order: 14 },
  overpaymentAmount: { label: 'Kwota nadpłaty', format: (v) => v > 0 ? new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v) : 'Brak', order: 15 },
  overpaymentFrequency: { label: 'Częstotliwość nadpłat', format: (v: string) => ({ 'one-time': 'Jednorazowa', monthly: 'Miesięczna', yearly: 'Roczna' }[v] || v), order: 16 },
  overpaymentStartMonth: { label: 'Miesiąc rozpoczęcia nadpłat', format: (v) => `${v}`, order: 17 },
  overpaymentTarget: { label: 'Cel nadpłat', format: (v: string) => ({ 'shorten-period': 'Skrócenie okresu', 'reduce-payment': 'Obniżenie rat' }[v] || v), order: 18 },
  overpaymentInterval: { label: 'Interwał nadpłat', format: (v) => `${v}`, order: 19 },
  
  // Wyniki wyceny
  price: { label: 'Szacowana wartość', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN', minimumFractionDigits: 0 }).format(v), order: 1 },
  minPrice: { label: 'Cena minimalna', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN', minimumFractionDigits: 0 }).format(v), order: 2 },
  maxPrice: { label: 'Cena maksymalna', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN', minimumFractionDigits: 0 }).format(v), order: 3 },
  currency: { label: 'Waluta', order: 4 },
  method: { label: 'Metoda wyceny', order: 5 },
  confidence: { label: 'Poziom ufności', format: (v) => `${v}`, order: 6 },
  note: { label: 'Uwagi', order: 7 },
  timestamp: { label: 'Data wyceny', format: (v) => new Date(v).toLocaleString('pl-PL'), order: 8 },
  
  // Wyniki zakupu nieruchomości
  pcctax: { label: 'Podatek PCC', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 1 },
  notaryFee: { label: 'Taksa notarialna', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 2 },
  bankCommissionAmount: { label: 'Prowizja banku', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 3 },
  courtFees: { label: 'Opłaty sądowe', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 4 },
  agencyCommissionAmount: { label: 'Prowizja agencji', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 5 },
  schedule: { label: 'Harmonogram spłat', order: 6 },
  
  // Wyniki flipera (agregaty)
  koszt_zakupu_brutto: { label: 'Koszty zakupu', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 1 },
  koszt_remontu_calkowity: { label: 'Koszty remontu', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 2 },
  koszty_utrzymania: { label: 'Koszty utrzymania', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 3 },
  koszty_finansowania: { label: 'Koszty finansowania', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 4 },
  koszty_calkowite: { label: 'Koszty całkowite', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 5 },
  koszty_sprzedazy: { label: 'Koszty sprzedaży', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 6 },
  zysk_brutto: { label: 'Zysk brutto (przed podatkiem)', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 7 },
  podatek: { label: 'Podatek', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 8 },
  zysk_netto: { label: 'Zysk netto', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 9 },
  ROI: { label: 'ROI', format: (v) => `${Number(v).toFixed(2)}%`, order: 10 },
  czas_trwania_flipa: { label: 'Czas trwania flipa (mies.)', order: 11 },
  sredni_miesieczny_zysk_netto: { label: 'Śr. mies. zysk netto', format: (v) => new Intl.NumberFormat('pl-PL', { style: 'currency', currency: 'PLN' }).format(v), order: 12 },
}; 