[build]
builder = "DOCKERFILE"

[deploy]
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
NODE_VERSION = "18"
PORT = "3000"
NEXT_TELEMETRY_DISABLED = "1"

# Environment variables (ustaw w Railway dashboard)
# DATABASE_URL = "postgresql://..."
# NEXTAUTH_SECRET = "..."
# NEXTAUTH_URL = "https://your-app.railway.app" 